[build]
  command = "npm install && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_DEBUG = "false"
  CI = "false"
  PUBLIC_URL = "/"
  SKIP_PREFLIGHT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  ESLINT_NO_DEV_ERRORS = "true"

# Редирект для имитации поведения React Router на локальной разработке
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Оптимизация кеширования для статических ресурсов
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.(jpg|jpeg|png|gif|webp|svg|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.(woff|woff2|ttf|otf|eot)"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
