[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"
  CI = "false"
  PUBLIC_URL = ""

# Single redirect rule for SPA - обновленная версия
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optimize asset caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
