[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  NODE_OPTIONS = ""
  PUBLIC_URL = "./"

# Редирект для имитации поведения React Router на локальной разработке
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Оптимизация кеширования для статических ресурсов
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
