[build]
  publish = "dist"
  command = "npm install && npm run build"
  environment = { NODE_VERSION = "18", NPM_VERSION = "10", PRESERVE_SESSION = "true" }

[dev]
  port = 8888
  targetPort = 5173
  publish = "dist"
  framework = "vite"

# Настройки функций - убедитесь, что внешние зависимости корректно определены
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]
  included_files = ["netlify/functions/*.cjs"]
  
# Отключаем встроенный бандлер для mongodb, чтобы избежать проблем с нативными зависимостями
[functions.mongodb]
  included_files = []
  external_node_modules = ["mongodb"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
