[build]
  command = "npm install && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = [
    "https://i\\.imgur\\.com/.*",
    "https://image\\.unsplash\\.com/.*",
    "https://images\\.unsplash\\.com/.*",
    "https://same-assets\\.com/.*"
  ]

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PRESERVE_SESSION = "true"

# FaunaDB configuration is managed via Netlify environment variables
# Set these in the Netlify UI:
# - FAUNA_SECRET - Client-side app secret (limited permissions)
# - FAUNA_ADMIN_KEY - Admin key used by serverless functions for setup
# - ADMIN_API_KEY - Secret key for accessing admin functions

[functions]
  directory = "netlify/functions"

# Run FaunaDB setup once at first deploy and then daily at 1:00 AM
[functions.setup-fauna]
  schedule = "0 1 * * *"

[[plugins]]
  package = "@netlify/plugin-functions"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
