[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"
  CI = "false"
  PUBLIC_URL = ""

# Основное правило редиректа для SPA - самый высокий приоритет
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Специальное правило для корневого пути
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Правила для конкретных маршрутов (добавьте все основные маршруты)
[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chats"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/chat/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/random-chat"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/guide"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
