[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"
  CI = "false"
  PUBLIC_URL = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Правила редиректа с самым высоким приоритетом
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Дополнительное правило для корневого пути
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

# Прямые правила для конкретных маршрутов
[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/profile"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/chats"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/chat/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/random-chat"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/guide"
  to = "/index.html"
  status = 200
  force = true

# Optimize asset caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
