[build]
  command = "npm run build && cp public/netlify-index.html build/index.html"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"
  CI = "true"

# Single redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optimize asset caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
