[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  # Установка нужной версии Node.js
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
