[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Установка нужной версии Node.js
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps --force"
  CI = "true"

# Правила редиректов для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
