[build]
  command = "node ./scripts/build-netlify.js"
  publish = "build"

[build.environment]
  # Установка нужной версии Node.js
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--no-audit --legacy-peer-deps"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
